/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  Token
} from '.././model'

export const getAPILoginMock = (overrideResponse: any = {}): Token => ({access_token: faker.word.sample(), token_type: faker.helpers.arrayElement([faker.word.sample(), undefined]), ...overrideResponse})

export const getAPIGetTokenMock = (overrideResponse: any = {}): Token => ({access_token: faker.word.sample(), token_type: faker.helpers.arrayElement([faker.word.sample(), undefined]), ...overrideResponse})


export const getAPILoginMockHandler = (overrideResponse?: Token) => {
  return http.post('*/api/auth/login', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getAPILoginMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getAPIGetTokenMockHandler = (overrideResponse?: Token) => {
  return http.post('*/api/auth/token', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getAPIGetTokenMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getAuthMock = () => [
  getAPILoginMockHandler(),
  getAPIGetTokenMockHandler()
]
