export const queryKeys = {
	GET_PLANT_CATEGORIES: 'GET_PLANT_CATEGORIES',
	GET_PLANTS: 'GET_PLANTS',
	GET_PLANT_DETAIL: 'GET_PLANT_DETAIL',
	GET_PLANT_PHOTOS: 'GET_PLANT_PHOTOS',
	GET_PLANT_STEPS: 'GET_PLANT_STEPS',
	GET_PLANT_STEP_TYPES: 'GET_PLANT_STEP_TYPES',
	GET_PLANT_STEP_DAY: 'GET_PLANT_STEP_DAY',
	GET_PLANT_RECIPES: 'GET_PLANT_RECIPES',
};
