/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.9
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query'
import type {
  InfiniteData,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  User
} from '../model/user'



/**
 * Returns the current user profile
 * @summary Get Current User Profile
 */
export const aPIGetCurrentUserProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    return axios.get(
      `https://api.zrosty-hay.simple2b.net/api/users/me`,options
    );
  }


export const getAPIGetCurrentUserProfileQueryKey = () => {
    return [`https://api.zrosty-hay.simple2b.net/api/users/me`] as const;
    }

    
export const getAPIGetCurrentUserProfileInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAPIGetCurrentUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>> = ({ signal }) => aPIGetCurrentUserProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData> & { queryKey: QueryKey }
}

export type APIGetCurrentUserProfileInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>>
export type APIGetCurrentUserProfileInfiniteQueryError = AxiosError<unknown>

/**
 * @summary Get Current User Profile
 */
export const useAPIGetCurrentUserProfileInfinite = <TData = InfiniteData<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getAPIGetCurrentUserProfileInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getAPIGetCurrentUserProfileQueryOptions = <TData = Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAPIGetCurrentUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>> = ({ signal }) => aPIGetCurrentUserProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData> & { queryKey: QueryKey }
}

export type APIGetCurrentUserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>>
export type APIGetCurrentUserProfileQueryError = AxiosError<unknown>

/**
 * @summary Get Current User Profile
 */
export const useAPIGetCurrentUserProfile = <TData = Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getAPIGetCurrentUserProfileQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



