/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  User
} from '.././model'

export const getAPIGetCurrentUserProfileMock = (overrideResponse: any = {}): User => ({activated: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), email: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), username: faker.word.sample(), ...overrideResponse})


export const getAPIGetCurrentUserProfileMockHandler = (overrideResponse?: User) => {
  return http.get('*/api/users/me', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getAPIGetCurrentUserProfileMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getUsersMock = () => [
  getAPIGetCurrentUserProfileMockHandler()
]
