/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.9
 */

export type APIGetAllParams = {
name?: string;
category_uuids?: string[];
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
size?: number;
};
