/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */

export type CareType = typeof CareType[keyof typeof CareType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CareType = {
  easy: 'easy',
  normal: 'normal',
  hard: 'hard',
} as const;
