/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
