/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */
import type { Plant } from './plant';
import type { PagePlantPage } from './pagePlantPage';
import type { PagePlantPages } from './pagePlantPages';
import type { PagePlantSize } from './pagePlantSize';
import type { PagePlantTotal } from './pagePlantTotal';

export interface PagePlant {
  items: Plant[];
  page: PagePlantPage;
  pages?: PagePlantPages;
  size: PagePlantSize;
  total: PagePlantTotal;
}
