/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.9
 */
import type { PhotoOriginalName } from './photoOriginalName';

export interface Photo {
  originalName: PhotoOriginalName;
  urlPath: string;
}
