/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.11
 */

export interface PlantDetail {
  features: string;
  generalInfo: string;
  humidityPercentage: number;
  isSunLoving: boolean;
  maxSize: number;
  minSize: number;
  name: string;
  temperatureInfo: string;
  uuid: string;
  wateringInfo: string;
  waterVolume: number;
}
