/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.8
 */

export type PlantFamilyType = typeof PlantFamilyType[keyof typeof PlantFamilyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlantFamilyType = {
  vegetable: 'vegetable',
  fruit: 'fruit',
  berry: 'berry',
} as const;
