/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.9
 */
import type { Photo } from './photo';

export interface PlantDetail {
  features: string;
  generalInfo: string;
  humidityPercentage: number;
  isSunLoving: boolean;
  maxSize: number;
  minSize: number;
  name: string;
  photos: Photo[];
  temperatureInfo: string;
  uuid: string;
  wateringInfo: string;
  waterVolume: number;
}
