/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.9
 */
import type { CareType } from './careType';
import type { PlantMaxTemperature } from './plantMaxTemperature';
import type { PlantMinTemperature } from './plantMinTemperature';
import type { PlantPhoto } from './plantPhoto';

export interface Plant {
  careType: CareType;
  isSunLoving: boolean;
  maxSize: number;
  maxTemperature: PlantMaxTemperature;
  minSize: number;
  minTemperature: PlantMinTemperature;
  name: string;
  photo: PlantPhoto;
  uuid: string;
  watering: CareType;
}
