/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.8
 */

export interface User {
  activated?: boolean;
  email: string;
  id: number;
  username: string;
}
